### ISSUE TITLE
Autor da notificação

### ISSUE THREAD

**Issue by miguelpeixe** [aetrapp/aetrapp#32]
Se for haver controle/relatório de broadcasts/notificações é importante que o modelo armazene o id do usuário que enviou a mensagem.

**Comment by vgeorge** [comment]
Adicionei a propriedade senderId às notificações: https://github.com/aetrapp/aetrapp/commit/e0d77eb961a57574eee916b68b5a3b01da403466

**Comment by vgeorge** [comment]
É preciso reiniciar a máquina docker ou executar a migração manualmente para ter efeito

**Comment by miguelpeixe** [comment]
não faz mais sentido só pegar o userId que já está conectado realizando a operação? me parece exposto demais esse método
